info:
    version: ""
    title: data_source_huaweicloud_ces_host_configurations
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: CES
paths:
    /V1.0/{project_id}/event-data:
        GET:
            tag: CES
