info:
    version: ""
    title: data_source_huaweicloud_hss_cicd_configurations
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: HSS
paths:
    /v5/{project_id}/image/cicd/configurations:
        GET:
            tag: HSS
