info:
    version: ""
    title: data_source_huaweicloud_hss_configs
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: HSS
paths:
    /v5/{project_id}/config:
        POST:
            tag: HSS
