info:
    version: ""
    title: data_source_huaweicloud_apig_application_authorize_statistic
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: APIG
paths:
    /v2/{project_id}/apigw/instances/{instance_id}/resources/outline/apps:
        GET:
            tag: APIG
