name: Terraform Lint
on: [push, pull_request]

jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Terraform Scripts Lint
        uses: Lance52259/hcbp-scripts-lint@v1.1.0
    with:
        fail-on-error: 'true'
        changed-files-only: 'true'
